---
- name: OpenLDAP Installation
  hosts: ldapserver
  remote_user: root
  become: true
  tasks:
  - name: YUM OpenLDAP
    yum:
      name:
        - 'openldap*'
        - nss-pam-ldapd
        - pam_ldap
        - autofs
        - nfs-utils
      state: latest

# ---
# - name: OpenLDAP Installation
#   hosts: ldapserver
#   remote_user: root
#   become: true
#   vars:
#     local_path: /var/lib/awx/projects/sw
#     ldap_path: /root
#   tasks:
#   - name: YUM OpenLDAP
#     yum:
#       name:
#         - 'openldap*'
#         - nss-pam-ldapd
#         - pam_ldap
#         - autofs
#         - nfs-utils
#       state: latest
#   - name: OpenLDAP Daemon Config
#     service:
#       name: slapd
#       state: started
#       enabled: yes
#   - name: Copy DB Config
#     copy:
#       src: "/usr/share/openldap-servers/DB_CONFIG.example"
#       dest: "/var/lib/ldap/DB_CONFIG"
#       remote_src: yes

#   - name: Chown DB_CONFIG
#     file:
#       path: "/var/lib/ldap/DB_CONFIG"
#       owner: ldap
#       group: ldap

#   - name: Send Script to openldap server
#     copy:
#       src: "{{ local_path }}/ldap_db_config.sh"
#       dest: "{{ ldap_path }}/ldap_db_config.sh"
#       mode: 0700

#   - name: Run db_config.sh
#     shell:
#       cmd: |
#         {{ ldap_path }}/ldap_db_config.sh




