---
- name: Grafana Installation
  hosts: grafana
  remote_user: root
  become: true
  tasks:

  - name: touch grafana.repo
    file:
      path: /etc/yum.repos.d/grafana.repo
      state: touch

  - name: Insert grafana.repo
    lineinfile:
      path: /etc/yum.repos.d/grafana.repo
      line: "[grafana]\nname=grafana\nbaseurl=https://packages.grafana.com/oss/rpm\nrepo_gpgcheck=1\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.grafana.com/gpg.key\nsslverify=1\nsslcacert=/etc/pki/tls/certs/ca-bundle.crt"

  - name: Show grafana.repo
    shell: cat /etc/yum.repos.d/grafana.repo
    register: grafana_repo

  - name: Show grafana.repo
    debug:
      msg: "{{ grafana_repo }}"

  - name: Yum grafana wget unzip
    yum:
      name:
        - grafana
        - wget
        - unzip

  - name: Service Start grafana
    service:
      name: grafana-server
      state: started

  - name: Service Enable grafana
    service:
      name: grafana-server
      enabled: yes
  
  - name: wget loki
    get_url: 
      url: https://github.com/grafana/loki/releases/download/v2.5.0/loki-linux-amd64.zip
      dest: /root/

  - name: unzip loki
    unarchive:
      src: /root/loki-linux-amd64.zip
      dest: /root/
      remote_src: yes